########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

BASE_UBUNTU_BOX_NAME = 'precise64'
BASE_UBUNTU_BOX_URI = 'http://files.vagrantup.com/precise64.box'

VIRTUALENV = 'feeder'

Vagrant.configure('2') do |config|

  config.vm.define :feeder do |feeder|

    feeder_ip = '10.0.1.2'

    feeder.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    feeder.vm.box = BASE_UBUNTU_BOX_NAME
    feeder.vm.box_url = BASE_UBUNTU_BOX_URI
    feeder.vm.network :private_network, ip: feeder_ip
    feeder.vm.hostname = 'feeder'

    command = """
      echo bootstrapping...

      # update
      echo updating db
      sudo apt-get -y update &&

      # install prereqs
      echo installing prerequisites
      sudo apt-get install -y python-setuptools python-dev vim
      sudo apt-get purge pip
      sudo easy_install -U pip
      sudo wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python

      # go home
      cd ~

      # virtualenv
      echo installing virtualenv
      sudo pip install virtualenv==1.11.4
      sudo pip install virtualenvwrapper
      # echo 'source /usr/local/bin/virtualenvwrapper.sh' >> /home/vagrant/.bashrc
      # source /usr/local/bin/virtualenvwrapper.sh
      echo creating #{VIRTUALENV} virtualenv
      # mkvirtualenv feeder
      # workon feeder
      virtualenv #{VIRTUALENV}
      source #{VIRTUALENV}/bin/activate

      # install feeder
      echo installing feeder
      pip install feeder

      echo bootstrap done.
      """
    feeder.vm.provision :shell do |sh|
      sh.privileged = false
      sh.inline = command
    end

  end

end